### PR TITLE
Bump build number to trigger python 3.9 rebuild

### PR DESCRIPTION
**Pull request by izahn**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
I'm not 100% sure that this will do the trick; the problem I'm trying to solve is

```
$ mamba create -n test4 rchitect python=3.9                                                                                                  (mamba) 

Looking for: ['rchitect', 'python=3.9']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
Encountered problems while solving.
Problem: package rchitect-0.3.30-py38h7f98852_0 requires python_abi 3.8.* *_cp38, but none of the providers can be installed
```

**Comment by jdblischak** [comment]
@izahn I don't think this is going to work. While conda-forge has built [Python 3.9](https://anaconda.org/conda-forge/python/files?version=3.9.2), they haven't yet updated the [pinning repository](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/ebc20348312733755f18850ceb739ad1db14ad1c/recipe/conda_build_config.yaml#L600).

```
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.6.* *_cpython    # [not (osx and arm64)]
  - 3.7.* *_cpython    # [not (osx and arm64)]
  - 3.8.* *_cpython
```

I assume there is a discussion somewhere about when to update the pinning to include builds for Python 3.9, but I don't know where. I didn't see any Issue or PR on the pinning repo itself. Until that changes, you won't be able to get this repo build with Python 3.9. If it's really important to you, you could build your own binary locally with Python 3.9 and upload it to your personal Anaconda Cloud channel.

**Comment by izahn** [comment]
Right, and looking at https://conda-forge.org/docs/maintainer/knowledge_base.html#build-matrices I would have expected this recipe to result in separate builds for each conda-forge supported python version. Maybe the specific python version requirements are interfering the the python build matrix detection?

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
Getting better, but still no python 3.9...

**Comment by izahn** [comment]
Bingo! This PR now adds support for python 3.6., 3.7, and 3.9. Checks all pass, ready to merge @jdblischak @randy3k !

**Comment by jdblischak** [comment]
Ok, I see the problem now. It was only built for Python 3.8: https://anaconda.org/conda-forge/rchitect/files?version=0.3.30

Could you please provide more context for how you created the file `.ci_support/python39.yml`? Did you use a tool like conda-smithy to generate it? Can you point to some documentation or other repos that use this strategy? I am used to repos following the official pinnings, so I'm concerned about breaking that. For example, in a future conda-smithy re-render where the pinnings include 3.9, will your bespoke file be automatically deleted or could it interfere with the re-rendering?

**Comment by izahn** [comment]
I followed the hints at https://gitter.im/conda-forge/conda-forge.github.io?at=6055262dad83ec3d7d3f8423 and 

1. copied `.ci_support/migrations/python39.yaml` from https://github.com/conda-forge/srwpy-feedstock/tree/master/.ci_support/migrations
2. ran `conda smithy rerender` to update all the CI and metadata files

Usually this would have happened via a bot PR to add a python39 build but that didn't happen because this package wasn't using the python build matrix.

**Comment by jdblischak** [comment]
Sounds good. Thanks for the explanation. Since you're clearly invested in this recipe, could you please add yourself as a maintainer? Then I'll merge this PR.

**Comment by izahn** [comment]
Done, thanks @jdblischak !

**Comment by izahn** [comment]
@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
Thanks @izahn!

**Pull request merged**
